### ISSUE TITLE
Error about annotation path when fine-tuning.

### ISSUE THREAD

**Issue by Retiina** [MegviiDetection/FSCE#6]
Dear author, thanks for your great work. I successfully train the pertained model, but when I fine-tuning, it reports such error:

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/vocsplit/box_10shot_aeroplane_train.txt'.

I have generate the shots by running `python datasets/prepare_voc_few_shot.py`.

**Comment by Chauncy-Cai** [comment]
prepare_voc_few_shot.pyb will generate files of 10 seeds, these files is put in 'datasets/vocsplit/seed*' (e.g.  'datasets/vocsplit/seed1' ). You need to choose the file set you want and put them in a correct address.
You can also get them from [http://dl.yf.io/fs-det/datasets/cocosplit/](url)

**Comment by Chauncy-Cai** [comment]
@Retiina 

`prepare_voc_few_shot.py` by default generate 10 seeds (suffix 0-9). The default seed used in literature is seed0. The author of FsDet implement it such that, when a seed is not specified, it will look for `box_[k]shot_*.txt` in `datasets/vocsplit` instead of `datasets/vocsplit/seed0`. 

We follow the same design. So you can try something like `cp datasets/vocsplit/seed0/* datasets/vocsplit` to move the desired shots data to `datasets/vocsplit` directory

And for COCO, you may also need `coco/datasplit` which can be downloaded from http://dl.yf.io/fs-det/datasets/

**Comment by Retiina** [comment]
@Chauncy-Cai , but when I run `prepare_voc_few_shot.py`, it generates suffix 1-10

**Comment by Chauncy-Cai** [comment]
seed0 is under this path: http://dl.yf.io/fs-det/datasets/vocsplit/ 
(all the file box_[k]shot_*.txt under this path is few-shot annotation of seed0)

**Comment by Retiina** [comment]
Thank you!

**Comment by Retiina** [comment]
@Chauncy-Cai , thanks for your help I successfully run the experiment of base training and 1 shot fine-tuning. But surprising, I got 43.456 nAP50 for split1 shot0 using `1shot_baseline.py`, is it normal, here is the result, which is higher than it reported in the paper (39.8). 

[03/21 23:11:04] fsdet.evaluation.pascal_voc_evaluation INFO: Evaluate overall bbox:
|   AP   |  AP50  |  AP75  |  bAP   |  bAP50  |  bAP75  |  nAP   |  nAP50  |  nAP75  |
|:------:|:------:|:------:|:------:|:-------:|:-------:|:------:|:-------:|:-------:|
| 41.377 | 69.769 | 43.106 | 47.264 | 78.540  | 49.770  | 23.714 | 43.456  | 23.113  |

**Comment by nothingelse92** [comment]
39.8 is reported in TFA, however, our so-called "baseline" is not the same as TFA, please refer to our paper for details. BTW, your reproduced result is reasonable.
